# Generated by Django 4.1.2 on 2022-10-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='transaction',
            field=models.CharField(choices=[('I', 'IN'), ('O', 'OUT')], max_length=1),
        ),
    ]
